### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by rbramley** [gofair-foundation/qualification-issue-creation-action#15]
Received a 422 response after creating about 80 issues in ~5 seconds, the error seems misleading as the label in question already exists:

```RequestError [HttpError]: Validation Failed: {"value":"Structured-vocabulary","resource":"Label","field":"name","code":"invalid"}
    at /home/runner/work/_actions/gofair-foundation/qualification-issue-creation-action/v0.5.1/dist/index.js:6883:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.createIssue (/home/runner/work/_actions/gofair-foundation/qualification-issue-creation-action/v0.5.1/dist/index.js:165470:3) {
  status: 422,
  response: {
    url: 'https://api.github.com/repos/gofair-foundation/fsr_qualification/issues',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-length': '208',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 21 Nov 2023 09:39:07 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-github-permissions': 'issues=write',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '18DB:0BA3:96F467:13C788D:655C7ABA',
      'x-ratelimit-limit': '1000',
      'x-ratelimit-remaining': '998',
      'x-ratelimit-reset': '1700563143',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '2',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Validation Failed',
      errors: [
        {
          value: 'Structured-vocabulary',
          resource: 'Label',
          field: 'name',
          code: 'invalid'
        }
      ],
      documentation_url: 'https://docs.github.com/rest/issues/issues#create-an-issue'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/gofair-foundation/fsr_qualification/issues',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/20.0.2 octokit-core.js/5.0.1 Node.js/20.8.1 (linux; x64)',
      'x-github-api-version': '2022-11-28',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"title":"QLIT | Queer Literature Indexing Thesaurus","body":"http://purl.org/np/RAd6t6NdoESOhEi4f2MC-yJ-l3ko8za5jjdrBVOdg6BMY","labels":["Structured-vocabulary","Semantic-model"]}',
    request: { hook: [Function: bound bound register] }
  }
}
```

The documentation for Create Issue lists the 422 return code with the description: "Validation failed, or the endpoint has been spammed."

**Comment by rbramley** [comment]
There is a specific Octokit plugin to handle this:
https://github.com/octokit/plugin-throttling.js/

**Comment by rbramley** [comment]
The [best practices](https://docs.github.com/en/rest/guides/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#pause-between-mutative-requests) guide says:

_If you are making a large number of POST, PATCH, PUT, or DELETE requests, wait at least one second between each request. This will help you avoid secondary rate limits._

**Comment by rbramley** [comment]
The plugin is quite easy to hook in, but has broken a number of tests.

**Comment by rbramley** [comment]
Note that we got a slightly different error from action v0.6:
```equestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID B861:2A1B:30B908A:656773F:655E25F7.```

**Comment by rbramley** [comment]
This isn't blocking progress, was able to import all of the issues in 4 runs.

**Comment by rbramley** [comment]
Closing as won't fix - the volume of issues shouldn't be as large as the initial import, and if necessary it can be run successfully over several attempts.
